"""add task_id to documents

Revision ID: 47857af26b87
Revises: db4c0376eabc
Create Date: 2026-06-01 10:35:42.439577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47857af26b87'
down_revision: Union[str, Sequence[str], None] = 'db4c0376eabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_task_id'), 'documents', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_task_id'), table_name='documents')
    op.drop_column('documents', 'task_id')
    # ### end Alembic commands ###
