"""add storage path to documents

Revision ID: a1de9c9e30fe
Revises: 5ee72ab87372
Create Date: 2026-05-27 10:25:21.387587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1de9c9e30fe'
down_revision: Union[str, Sequence[str], None] = '5ee72ab87372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
