"""add rag qa records

Revision ID: db4c0376eabc
Revises: cab68e395794
Create Date: 2026-05-27 21:53:02.031872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4c0376eabc'
down_revision: Union[str, Sequence[str], None] = 'cab68e395794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_qa_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_qa_records_id'), 'rag_qa_records', ['id'], unique=False)
    op.create_index(op.f('ix_rag_qa_records_knowledge_base_id'), 'rag_qa_records', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_rag_qa_records_user_id'), 'rag_qa_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_qa_records_user_id'), table_name='rag_qa_records')
    op.drop_index(op.f('ix_rag_qa_records_knowledge_base_id'), table_name='rag_qa_records')
    op.drop_index(op.f('ix_rag_qa_records_id'), table_name='rag_qa_records')
    op.drop_table('rag_qa_records')
    # ### end Alembic commands ###
