DOCUMENT_STATUS_PENDING = "pending"
DOCUMENT_STATUS_QUEUED = "queued"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_COMPLETED = "completed"
DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUS_CANCELLED = "cancelled"


DOCUMENT_RUNNING_STATUSES = [
    DOCUMENT_STATUS_QUEUED,
    DOCUMENT_STATUS_PROCESSING,
]


DOCUMENT_RETRYABLE_STATUSES = [
    DOCUMENT_STATUS_PENDING,
    DOCUMENT_STATUS_FAILED,
    DOCUMENT_STATUS_CANCELLED,
]
